### PR TITLE
mv .envrc → .envrc.example

### PR DESCRIPTION
**Pull request by toastal**
It isn’t a good idea to make a personal configuration file hard to work with since it’s being tracked by the repository. This will a) trigger ``direnv`` to fire off its allow script before a use gets a chance to see what arbitrary code is about to be executed on their behalf & b) make making modifications more difficult as it would be easy to accidentally commit those modifications *or* requires addings all sorts of unnecessary extra configuration to allow a safe place to put in custom environment variables.

The simple solution is to just leave an example for those that want it.

### CODE REVIEW

**Comment by Janik-Haag** [comment]
We already had this discussion and the overall sentiment seems to be that the it's currently handle is fine. https://github.com/NixOS/nixfmt/pull/118#discussion_r1514230533

**Comment by piegamesde** [comment]
Yes, we forgot to do that unfortunately.

**Comment by infinisil** [comment]
I'd be okay with something like this though:

```bash
if [[ -f .envrc.local ]]; then
  source .envrc.local
else
  use_nix
fi
```

This will allow you to customise the behavior without changing the default.

**Comment by dasJ** [comment]
You woldn't: https://github.com/direnv/direnv/issues/348#issuecomment-571168850

**Pull request closed without merging**
