### PR TITLE
Automated Nixpkgs diffs for PRs

### PR DESCRIPTION
**Pull request by infinisil**
Implements #163 (see for more context) by reusing the script [from before](https://github.com/piegamesde/nixfmt/pull/1). I took the time to clean up the script to a reasonable degree now though :)

For now it won't work for PRs from forks, but in turn it should work for this PR itself, let's see..

### CODE REVIEW

**Comment by tomberek** [comment]
A reasonable link to generate and put into the status? https://github.com/infinixbot/nixpkgs/compare/nixfmt-186~2...infinixbot:nixpkgs:nixfmt-186

**Review by tomberek — APPROVED** [review]
does what it claims to

**Review by 0x4A6F — APPROVED** [review]
Thanks

**Comment by infinisil** [comment]
@tomberek Yeah we could do that, I'd say let's merge this for now, I'll improve this in follow-up PRs

**Comment by infinisil** [comment]
See https://github.com/NixOS/nixfmt/issues/187#issuecomment-2040729223 for a mock-up of how it could look :)

**Pull request merged**
