### PR TITLE
[SIO-379] Prohibit indexation of subdomains

### PR DESCRIPTION
**Pull request by a-matson**
Problem: This page is indexed.

Solution: Add metatag to prohibit this.

### CODE REVIEW

**Comment by yorickvP** [comment]
Why should this page not be indexed? I think we want it to show up in google.

**Comment by a-matson** [comment]
This is the request of marketing https://issues.serokell.io/issue/SIO-379. You may ask Olga for clarification

**Comment by yorickvP** [comment]
I'm no longer in the Serokell slack nor do I work there, could you ask Olga for clarification for me?

**Comment by a-matson** [comment]
Asked. I will update

**Comment by Sereja313** [comment]
As of https://github.com/NixOS/nixfmt/pull/162, this repository is no longer associated with https://nixfmt.serokell.io/. Everything related to it will be located at https://github.com/serokell/nixfmt-website. So I'm closing this PR

**Pull request closed without merging**
