### PR TITLE
Predoc: Fix quadratic complexities in nest and offset

### PR DESCRIPTION
**Pull request by dasJ**
I honestly don't understand why this makes it faster, but for me the test suite runs ~2s faster now. This is an AI-generated contribution. The GPT explanation is:

By abstracting the transformation logic into a single function `transform`, we can pass different transformations for nesting and offsetting. This way, we avoid repeated traversals and ensure each element is processed exactly once.

This change ensures linear complexity for the `nest` and `offset` functions. We leverage the `map` function to traverse and transform the `Doc` structure only once, applying the necessary changes to each element.

### CODE REVIEW

**Comment by piegamesde** [comment]
Someone who actually knows Haskell should vet this, but my gut feeling is that the complexity is still quadratic, and that the performance improvement is of other nature (or just measurement noise).

**Comment by dasJ** [comment]
Now that I look at it, isn't `nest x` the same as `offset 1 x`?

**Comment by piegamesde** [comment]
They're doing similar things but on different fields of `Text`

**Comment by MangoIV** [comment]
I cannot verify this speedup locally and I would be very surprised, this changes anything significantly. Unlike chatgpt claims, this does not remove any quadratic complexity, either, it just called map transform now, if you resubstitute you can see that.

**Comment by tchoutri** [comment]
From a cursory glance it appears that it is just a rephrasing of the previous code without real improvement on the data structures or operations.

**Comment by infinisil** [comment]
Let's close this then

**Pull request closed without merging**
